[package]
name = "kf"
version = "0.1.4"
authors = ["David Taylor <david.baker.taylor@gmail.com>"]
edition = "2018"
description = "Kalman filter"
license = "MIT"

[dependencies]
nalgebra = "0.21.0"
thiserror = "1.0.19"
fehler = "1.0.0"